development:
  adapter: postgresql
  encoding: unicode
  database: login-users
  pool: 5
  username: postgres
  password: root

test:
  adapter: postgresql
  encoding: unicode
  database: login-users
  pool: 5
  username: postgres
  password: root